version: '3'

services:
  db:
    image: postgres:16.3
    container_name: teslodb
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data:z