
@host=localhost:3000

# to delete an update
@id=df394065-574c-464f-90d4-72a4398fa8c5

# to search
@term=danilos_20_pants

###

GET http://{{host}}/api/products

###

GET http://{{host}}/api/products
    ?limit=10
    &offset=0

###

GET http://{{host}}/api/products/{{term}}

###

POST http://{{host}}/api/products
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjYWU2MWM3LTcxMWMtNDE1Yy05NjU0LWRjZWI3Nzg1MTk4OCIsImlhdCI6MTcxOTg1NzU2NiwiZXhwIjoxNzE5ODY0NzY2fQ.Nm9JrEo05iN2exfu0owkvYgJVVWOek9qNuVTLPP7Axk

{
  "title": "danilo's 23 pants",
  "sizes": ["S","M"],
  "gender": "men",
  "price": 100.34,
  "images": [
    "http://imagen3.png",
    "http://imagen4.png"
  ]
}

###

PATCH http://{{host}}/api/products/{{id}}
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjYWU2MWM3LTcxMWMtNDE1Yy05NjU0LWRjZWI3Nzg1MTk4OCIsImlhdCI6MTcxOTg1NzU2NiwiZXhwIjoxNzE5ODY0NzY2fQ.Nm9JrEo05iN2exfu0owkvYgJVVWOek9qNuVTLPP7Axk

{
  "price": 900.00,
  "images": [
    "https://imagen3.png",
    "https://imagen4.png",
    "https://imagen5.png",
    "https://imagen6.png",
    "https://imagen7.png",
    "https://imagen8.png"
  ]
}

###

DELETE  http://{{host}}/api/products/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjYWU2MWM3LTcxMWMtNDE1Yy05NjU0LWRjZWI3Nzg1MTk4OCIsImlhdCI6MTcxOTg1NzU2NiwiZXhwIjoxNzE5ODY0NzY2fQ.Nm9JrEo05iN2exfu0owkvYgJVVWOek9qNuVTLPP7Axk
###
